# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  print_fail:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: return 1
      - run:
          name: print hello world on failure of last step
          command: echo "hello world"
          when: on_fail

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the welcome/run job in its own container
    jobs:
      - print_fail